name: HTML Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download HTML file
      uses: actions/http-client@v2
      with:
        url: 'https://raw.githubusercontent.com/Hari20042002/new-repo/main/index.html'
        dest: 'index.html'

    - name: Transfer HTML file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "index.html"
        target: "/home/ubuntu/Github"
         
