name: HTML Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        sshkey: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          SOURCE_PATH="${{ secrets.SOURCE_PATH }}"
          DESTINATION_PATH="${{ secrets.DESTINATION_PATH }}"
          mkdir -p "$DESTINATION_PATH"
          cp -r "$SOURCE_PATH"/* "$DESTINATION_PATH"  

         
